# windows_backup_task.ps1 — Run as Administrator
# Part of faerie2 vault collaboration setup
#
# Installs a Windows Task Scheduler entry that runs vault backup (5b_vault_backup.py)
# via WSL on a recurring schedule. Equivalent to cron 0 * * * * on macOS/Linux.
#
# This script is auto-generated by 5c_install_backup_cron.py but can also be
# run standalone. Edit the variables at the top to match your paths.
#
# Usage (PowerShell, run as Administrator):
#   .\windows_backup_task.ps1
#   .\windows_backup_task.ps1 -Interval 6h
#   .\windows_backup_task.ps1 -Interval daily
#   .\windows_backup_task.ps1 -Remove
#   .\windows_backup_task.ps1 -Status

param(
    # Interval: 1h | 6h | daily
    [ValidateSet("1h", "6h", "daily")]
    [string]$Interval = "1h",

    # Full path to 5b_vault_backup.py (WSL-side path)
    [string]$BackupScript = "/mnt/d/0LOCAL/gitrepos/faerie2/scripts/5b_vault_backup.py",

    # Log file (WSL-side path)
    [string]$LogFile = "/mnt/c/Users/$env:USERNAME/.claude/logs/vault-backup.log",

    # Remove the scheduled task
    [switch]$Remove,

    # Show task status
    [switch]$Status
)

$TaskName    = "faerie-vault-backup"
$TaskDesc    = "faerie vault backup to B2 — managed by windows_backup_task.ps1"

Write-Host ""
Write-Host "faerie2 Vault Backup — Windows Task Scheduler"
Write-Host ("=" * 50)

# --- Status mode ---
if ($Status) {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) {
        Write-Host "  Task '$TaskName': INSTALLED"
        Write-Host "  State:   $($task.State)"
        $info = Get-ScheduledTaskInfo -TaskName $TaskName -ErrorAction SilentlyContinue
        if ($info) {
            Write-Host "  Last run:  $($info.LastRunTime)"
            Write-Host "  Last result: $($info.LastTaskResult)"
            Write-Host "  Next run:  $($info.NextRunTime)"
        }
    } else {
        Write-Host "  Task '$TaskName': NOT INSTALLED"
    }
    exit 0
}

# --- Remove mode ---
if ($Remove) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "  [OK] Task '$TaskName' removed."
    } else {
        Write-Host "  [INFO] Task '$TaskName' not found — nothing to remove."
    }
    exit 0
}

# --- Check WSL is available ---
$wslPath = (Get-Command wsl.exe -ErrorAction SilentlyContinue)?.Source
if (-not $wslPath) {
    Write-Host "  [ERROR] wsl.exe not found. Enable WSL first."
    Write-Host "  wsl --install"
    exit 1
}

# --- Build trigger ---
switch ($Interval) {
    "1h" {
        $trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 1) `
                     -Once -At (Get-Date)
        $schedDesc = "Every 1 hour"
    }
    "6h" {
        $trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 6) `
                     -Once -At (Get-Date)
        $schedDesc = "Every 6 hours"
    }
    "daily" {
        $trigger = New-ScheduledTaskTrigger -Daily -At "03:00"
        $schedDesc = "Daily at 03:00"
    }
}

# --- Build action ---
# Run: wsl.exe python3 /path/to/5b_vault_backup.py >> /path/to/vault-backup.log 2>&1
$wslCmd = "python3 $BackupScript >> $LogFile 2>&1"
$action = New-ScheduledTaskAction `
    -Execute "wsl.exe" `
    -Argument "-e bash -c `"$wslCmd`""

# --- Settings ---
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable:$false `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2) `
    -MultipleInstances IgnoreNew

# --- Check if already installed ---
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "  [INFO] Task '$TaskName' already installed."
    Write-Host "  Use -Remove to uninstall, then re-run to reinstall with new settings."
    Write-Host ""
    $info = Get-ScheduledTaskInfo -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($info) {
        Write-Host "  Next run: $($info.NextRunTime)"
    }
    exit 0
}

# --- Register task ---
Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Description $TaskDesc `
    -RunLevel Highest `
    -Force | Out-Null

$task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($task) {
    Write-Host "  [OK] Task '$TaskName' installed."
    Write-Host "  Schedule: $schedDesc"
    Write-Host "  Script:   $BackupScript"
    Write-Host "  Log:      $LogFile"
    Write-Host ""
    Write-Host "  To run now:   Start-ScheduledTask -TaskName '$TaskName'"
    Write-Host "  To check:     .\windows_backup_task.ps1 -Status"
    Write-Host "  To remove:    .\windows_backup_task.ps1 -Remove"
} else {
    Write-Host "  [ERROR] Task registration failed. Check you are running as Administrator."
    exit 1
}
